Ass2-war/src/java/controllers/CustomerController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package controllers;

import ejb.BookService;
import entities.Customer;
import entities.UserGroup;
import helper.PasswordConverter;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;

/**
 *
 * @author Alex
 */
@Named(value = "customerController")
@SessionScoped
public class CustomerController implements Serializable {

    /**
     * Creates a new instance of CustomerController
     */
    @EJB
    BookService bookService;
    private Customer customer = new Customer();
    String password;
    String groupName;
    ArrayList<String> group = new ArrayList<String>();    
    @PostConstruct
    public void init() {
        group.add("admin");
        group.add("customer");
      
    }
    
    public String read(Customer customer) {
        this.customer = customer;
        return "customerManagement";
    }
    public String setupCreate() {
        customer = new Customer();
        return "customerManagement";
    }
    public Boolean checkCustomerName() {
        Boolean flag = true;
        for(Customer c: bookService.getAllUsers()){
            if(c.getName().equals(customer.getName())){
                flag = false;
            }
        }
        return flag;
        
    }
    public String create() {
        if(checkCustomerName()){
        customer.setPassword(PasswordConverter.convertString(password));
        bookService.addUser(customer);
        Customer cus = bookService.findByUserName(customer.getName());
        UserGroup userGroup = new UserGroup();
        userGroup.setGroupName(groupName);
        userGroup.setName(cus.getName());
        userGroup.setCus(cus);
        bookService.addUserGroup(userGroup);
        cus.setUserGroup(userGroup);
        bookService.updateUser(cus);
        return "index";
        }
        else {
            return null;
        }
    }
    
    
    public String update() {
        if(checkCustomerName()){
        bookService.deleteGroupUser(customer.getId());
        UserGroup userGroup = new UserGroup();
        userGroup.setGroupName(groupName);
        userGroup.setName(customer.getName());
        userGroup.setCus(customer);
        bookService.addUserGroup(userGroup);
        customer.setUserGroup(userGroup);
        customer.setPassword(PasswordConverter.convertString(password));
        bookService.updateUser(customer);   
        return "index";
        }
        else{
            return null;
        }
    }
    
    public String delete(Customer c) {
        try{
        bookService.deleteGroupUser(customer.getId());
        bookService.deleteUser(c);
        }
        catch (Exception e){
            ErrorController ec= new ErrorController();
            ec.setErrorMessage("The user can not be deleted");
            return "errorPage";         
        }
        return "index";
    }
    
    public List<Customer> getCustomers() {
        return bookService.getAllUsers();
    }

    public Customer getCustomer() {
        return customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;      
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public ArrayList<String> getGroup() {
        return group;
    }

    public void setGroup(ArrayList<String> group) {
        this.group = group;
    }
    
}

Ass2-war/src/java/controllers/IndexController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package controllers;

import ejb.BookService;
import entities.*;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.ApplicationScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.servlet.http.HttpSession;

/**
 *
 * @author Alex
 */
@Named(value = "indexController")
@ApplicationScoped
public class IndexController {
    
    
    @EJB
    BookService bookService;
    private String currentUsername;

        
    
    public String getCurrentUsername() {
        FacesContext facesContext = FacesContext.getCurrentInstance();
        currentUsername = facesContext.getExternalContext().getRemoteUser();
        return currentUsername;
    }

    public void setCurrentUsername(String currentUsername) {
        this.currentUsername = currentUsername;
    }
    
    
    public List<Customer> getUsers() {
        return bookService.getAllUsers();
    }
    
    public List<BookCategory> getBookCategories() {
        return bookService.getAllBookCategorys();
    }
    public List<BookCategory> getMarkedBook() {
        List<BookCategory> bcs = new ArrayList<BookCategory>();
        for(BookCategory bc: getBookCategories()){
            if(bc.getCustomers().size()>0){
                bcs.add(bc);
            }
        }
        return bcs;
    }
    public List<Book> getBooks() {
        return bookService.getAllBooks();
    }
   
    public String logout() {
    FacesContext facesContext = FacesContext.getCurrentInstance();
    HttpSession httpSession = (HttpSession)facesContext.getExternalContext().getSession(false);
    httpSession.invalidate();
    
    return "/faces/index";
    }
}

Ass2-war/web/admin/adminHeader.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
         <ui:composition>
            <header>
                
                    <div class="logo">
                        <h1>Monash Books</h1>
                        <h3>Your choice</h3>
                    </div>
               
                <ul id="navbar">
                    <li><h:link outcome="index">Home</h:link></li>
                    <li><h:form>
                            <h:commandLink action="#{bookController.setupCreate()}">Add Book</h:commandLink>
                    </h:form></li>
                    <li><h:form>
                            <h:commandLink action="#{customerController.setupCreate()}">Add Customer</h:commandLink>
                    </h:form></li>
                   
                    <li><b>Current user : </b>#{indexController.currentUsername}</li>
                    <li><h:form>
                            <h:commandButton action="#{indexController.logout()}" value="Logout"/>

                        </h:form></li>   
                </ul>
            </header>
        </ui:composition>
    </h:body>
</html>

Ass2-war/web/admin/bookManagement.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Facelet Title</title>
        <link href="style.css" rel="stylesheet" type="text/css"/>
    </h:head>
    <h:body>
        <ui:composition template="../masterpage.xhtml">
            <ui:define name="header">
                <ui:include src="adminHeader.xhtml" />
            </ui:define>
            <ui:define name="content">
                <div id="content">
                    <f:view>
                        <h:form id="myForm">
                            <h1><h:outputText value="Create/Edit Book"/></h1>
                            <h:panelGrid columns="2" style=" margin-left: 350px" >
                                <h:outputLabel value="Title:" for="title" />
                                <h:inputText id="title" value="#{bookController.bookCategory.title}"
                                             title="Title" />
                                <h:outputLabel value="Description:" for="description" />
                                <h:inputText id="description" value="#{bookController.bookCategory.description}"
                                             title="description" />
                                <h:outputLabel value="Author" for="author" />
                                <h:inputText id="author" value="#{bookController.bookCategory.author}"
                                             title="Author" />
                                <h:outputLabel value="Publisher" for="publisher" />
                                <h:inputText id="publisher" value="#{bookController.bookCategory.publisher}"
                                             title="Publisher" />
                                <h:outputLabel value="ISBN" for="ISBN" />
                                <h:inputText id="ISBN" value="#{bookController.bookCategory.isbn}"
                                             title="ISBN" />
                                <h:outputLabel value="Quantity" for="quantity" />
                                <h:inputText id="quantity" value="#{bookController.quantity}"
                                             title="Quantity" />
                                <h:outputLabel value="Publish Date" for="datepicker" />
                                <h:inputText class="datepicker" title="PubDate" value="#{bookController.bookCategory.publishDate}" />
                                
                            </h:panelGrid>
                            <h:commandButton id="create" 
                                             value="Create" rendered="#{empty bookController.bookCategory.id}" action="#{bookController.create()}"/>
                            <h:commandButton id="update" 
                                             value="Update" rendered="#{not empty bookController.bookCategory.id}" action="#{bookController.update()}"/>
                            <h:commandButton id="back" value="Back" action="index"/>
                        </h:form>
                    </f:view>
                </div>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

Ass2-war/web/admin/customerManagement.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition template="../masterpage.xhtml">
            <ui:define name="header">
                <ui:include src="adminHeader.xhtml" />
            </ui:define>
            <ui:define name="content">
                <div id="content">
                    <f:view>
                        <h:form>
                            <h1><h:outputText value="Create/Edit Customer"/></h1>
                            <h:panelGrid columns="2" style=" margin-left: 350px">
                                <h:outputLabel value="Name:" for="name" />
                                <h:inputText id="name" value="#{customerController.customer.name}"
                                             title="name" />
                                <h:outputLabel value="Password:" for="password" />
                                <h:inputText id="password" value="#{customerController.password}"
                                             title="password" />
                                <h:outputLabel value="Group:" for="group" />
                                <h:selectOneMenu id="group" value="#{customerController.groupName}">
                                    <f:selectItems value="#{customerController.group}"/> </h:selectOneMenu>

                            </h:panelGrid>
                            
                            <h:commandButton id="create" 
                                             value="Create" rendered="#{empty customerController.customer.id}" action="#{customerController.create()}"/>
                            <h:commandButton id="update" 
                                             value="Update" rendered="#{not empty customerController.customer.id}" action="#{customerController.update()}"/>
                            <h:commandButton id="back" value="Back" action="index"/>
                        </h:form>
                    </f:view>
                </div>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

Ass2-war/web/admin/errorPage.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition template="index.xhtml">
            <ui:define name="content">
                <div id="content">
                    #{errorController.error}                   
                </div>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

Ass2-war/web/admin/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Admin Page</title>
    </h:head>
    <h:body>
        <ui:composition template="../masterpage.xhtml">
            <ui:define name="header">
                <ui:include src="adminHeader.xhtml" />
            </ui:define>
            <ui:define name="content">
                <div id="content">
                    <f:view>
                        <h:form>
                            <h1><h:outputText value="Display Books"/></h1>
                            <h:dataTable value="#{indexController.bookCategories}" var="book">
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="Id"/>
                                    </f:facet>
                                    <h:outputText value="#{book.id}"/>
                                </h:column>
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="Title"/>
                                    </f:facet>
                                    <h:outputText value="#{book.title}"/>
                                </h:column>
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="author"/>
                                    </f:facet>
                                    <h:outputText value="#{book.author}"/>
                                </h:column>
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="Publisher"/>
                                    </f:facet>
                                    <h:outputText value="#{book.publisher}"/>
                                </h:column>
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="Publish Date"/>
                                    </f:facet>
                                    <h:outputText value="#{book.publishDate}"/>
                                </h:column>
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="ISBN"/>
                                    </f:facet>
                                    <h:outputText value="#{book.isbn}"/>
                                </h:column>
                                
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="Description"/>
                                    </f:facet>
                                    <h:outputText value="#{book.description}"/>
                                </h:column>
                            <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="Quantity"/>
                                    </f:facet>
                                    <h:outputText value="#{bookController.bookQuantity(book)}"/>
                                </h:column>
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="Actions"/>
                                    </f:facet>
                                    <h:commandButton action="#{bookController.read(book)}" value="Edit" />
                                    <h:commandButton action="#{bookController.delete(book)}" value="Delete" />
                                </h:column>
                            </h:dataTable>
                            <hr />
                            <h:commandButton action="#{bookController.setupCreate()}" value="Add new Book" />
                            <hr />
                            <h1><h:outputText value="Display Customers"/></h1>
                            <h:dataTable value="#{customerController.customers}" var="cus">
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="Id"/>
                                    </f:facet>
                                    <h:outputText value="#{cus.id}"/>
                                </h:column>
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="Name"/>
                                    </f:facet>
                                    <h:outputText value="#{cus.name}"/>
                                </h:column>
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="Password"/>
                                    </f:facet>
                                    <h:outputText value="#{cus.password}"/>
                                </h:column>
                                
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="Actions"/>
                                    </f:facet>
                                    <h:commandButton action="#{customerController.read(cus)}" value="Edit" />
                                    <h:commandButton action="#{customerController.delete(cus)}" value="Delete" />
                                </h:column>
                            </h:dataTable>
                            <hr />
                            <h:commandButton action="#{customerController.setupCreate()}" value="Add new Customer" />
                            <hr />          
                      </h:form>
                    </f:view>
                    
                </div>
            </ui:define>
        </ui:composition>
    </h:body>
</html>