Ass2-war/src/java/controllers/CommentController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package controllers;

import ejb.BookService;
import entities.BookCategory;
import entities.Comment;
import entities.Customer;
import helper.DateHelper;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.context.FacesContext;

/**
 *
 * @author Alex
 */
@Named(value = "commentController")
@SessionScoped
public class CommentController implements Serializable {

   @EJB
    BookService bookService;
    private Comment comment;
    private String commentMsg;
    private Customer cus;
    private BookCategory bc;

    public String createComment() {
        comment = new Comment();
        comment.setComment(commentMsg);
        comment.setCommentTime(DateHelper.getCurrentDate());
        for(Customer c: bookService.getAllUsers()){
            if(c.getName().equals(getCurrentUserName())){
                cus = c;
            }
        }
        comment.setCus(cus);
        comment.setBookCategory(bc);
        bookService.addComment(comment);
        bc.getComments().add(comment);
        cus.getComments().add(comment);
        bookService.updateBookCategory(bc);
        bookService.updateUser(cus);
        return "bookDetail";
    }
    public Comment getComment() {
        return comment;
    }
    
    public void setComment(Comment comment) {
        this.comment = comment;
    }

    public Customer getCus() {
        return cus;
    }

    public void setCus(Customer cus) {
        this.cus = cus;
    }
    public String getCurrentUserName() {
        FacesContext facesContext = FacesContext.getCurrentInstance();       
        return facesContext.getExternalContext().getRemoteUser();
    }
    public String getCommentMsg() {
        return commentMsg;
    }

    public void setCommentMsg(String commentMsg) {
        this.commentMsg = commentMsg;
    }
    public String readBookCategory(BookCategory bg) {
        this.bc = bg;
        return "bookDetail";
    }
    public List<Comment> getUserComment() {
        return bc.getComments();
    }

    public BookCategory getBc() {
        return bc;
    }

    public void setBc(BookCategory bc) {
        this.bc = bc;
    }
    
}

Ass2-war/src/java/controllers/CustomerController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package controllers;

import ejb.BookService;
import entities.Customer;
import entities.UserGroup;
import helper.PasswordConverter;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;

/**
 *
 * @author Alex
 */
@Named(value = "customerController")
@SessionScoped
public class CustomerController implements Serializable {

    /**
     * Creates a new instance of CustomerController
     */
    @EJB
    BookService bookService;
    private Customer customer = new Customer();
    String password;
    String groupName;
    ArrayList<String> group = new ArrayList<String>();    
    @PostConstruct
    public void init() {
        group.add("admin");
        group.add("customer");
      
    }
    
    public String read(Customer customer) {
        this.customer = customer;
        return "customerManagement";
    }
    public String setupCreate() {
        customer = new Customer();
        return "customerManagement";
    }
    public Boolean checkCustomerName() {
        Boolean flag = true;
        for(Customer c: bookService.getAllUsers()){
            if(c.getName().equals(customer.getName())){
                flag = false;
            }
        }
        return flag;
        
    }
    public String create() {
        if(checkCustomerName()){
        customer.setPassword(PasswordConverter.convertString(password));
        bookService.addUser(customer);
        Customer cus = bookService.findByUserName(customer.getName());
        UserGroup userGroup = new UserGroup();
        userGroup.setGroupName(groupName);
        userGroup.setName(cus.getName());
        userGroup.setCus(cus);
        bookService.addUserGroup(userGroup);
        cus.setUserGroup(userGroup);
        bookService.updateUser(cus);
        return "index";
        }
        else {
            return null;
        }
    }
    
    
    public String update() {
        if(checkCustomerName()){
        bookService.deleteGroupUser(customer.getId());
        UserGroup userGroup = new UserGroup();
        userGroup.setGroupName(groupName);
        userGroup.setName(customer.getName());
        userGroup.setCus(customer);
        bookService.addUserGroup(userGroup);
        customer.setUserGroup(userGroup);
        customer.setPassword(PasswordConverter.convertString(password));
        bookService.updateUser(customer);   
        return "index";
        }
        else{
            return null;
        }
    }
    
    public String delete(Customer c) {
        try{
        bookService.deleteGroupUser(customer.getId());
        bookService.deleteUser(c);
        }
        catch (Exception e){
            ErrorController ec= new ErrorController();
            ec.setErrorMessage("The user can not be deleted");
            return "errorPage";         
        }
        return "index";
    }
    
    public List<Customer> getCustomers() {
        return bookService.getAllUsers();
    }

    public Customer getCustomer() {
        return customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;      
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public ArrayList<String> getGroup() {
        return group;
    }

    public void setGroup(ArrayList<String> group) {
        this.group = group;
    }
    
}

Ass2-war/src/java/controllers/IndexController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package controllers;

import ejb.BookService;
import entities.*;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.ApplicationScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.servlet.http.HttpSession;

/**
 *
 * @author Alex
 */
@Named(value = "indexController")
@ApplicationScoped
public class IndexController {
    
    
    @EJB
    BookService bookService;
    private String currentUsername;

        
    
    public String getCurrentUsername() {
        FacesContext facesContext = FacesContext.getCurrentInstance();
        currentUsername = facesContext.getExternalContext().getRemoteUser();
        return currentUsername;
    }

    public void setCurrentUsername(String currentUsername) {
        this.currentUsername = currentUsername;
    }
    
    
    public List<Customer> getUsers() {
        return bookService.getAllUsers();
    }
    
    public List<BookCategory> getBookCategories() {
        return bookService.getAllBookCategorys();
    }
    public List<BookCategory> getMarkedBook() {
        List<BookCategory> bcs = new ArrayList<BookCategory>();
        for(BookCategory bc: getBookCategories()){
            if(bc.getCustomers().size()>0){
                bcs.add(bc);
            }
        }
        return bcs;
    }
    public List<Book> getBooks() {
        return bookService.getAllBooks();
    }
   
    public String logout() {
    FacesContext facesContext = FacesContext.getCurrentInstance();
    HttpSession httpSession = (HttpSession)facesContext.getExternalContext().getSession(false);
    httpSession.invalidate();
    
    return "/faces/index";
    }
}

Ass2-war/src/java/controllers/LoanController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package controllers;

import ejb.BookService;
import entities.Book;
import entities.BookCategory;
import entities.Customer;
import entities.Loan;
import helper.DateHelper;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.context.FacesContext;

/**
 *
 * @author Alex
 */
@Named(value = "loanController")
@SessionScoped
public class LoanController implements Serializable {

    @EJB
    BookService bookService;
    private Loan loan;
    private Customer cus;
    private Book b;
    private Boolean loanButton;
    
    public String createLoan(Book book) {
        loan = new Loan();
        String userName = getCurrentUserName();
        for(Customer c: bookService.getAllUsers()){
            if(c.getName().equals(userName)){
                cus = c;
            }
        }
        b = book;

        loan.setUser(cus);
        loan.setBook(b);
        loan.setLoanDate(DateHelper.getCurrentDate());
        b.getLoan().add(loan);
        cus.getLoan().add(loan);
        bookService.addLoan(loan);
        b.setAvailability(Boolean.FALSE);
        
        bookService.updateBook(b);
        bookService.updateUser(cus);
        return "index";
        
    }
    public String returnBook(Loan loan) {
        loan.getBook().setAvailability(true);
        bookService.updateBook(loan.getBook());
        bookService.deleteLoan(loan);
        return "manageLoan";
        
    }
    public String getCurrentUserName() {
        FacesContext facesContext = FacesContext.getCurrentInstance();       
        return facesContext.getExternalContext().getRemoteUser();
    }
    public Loan getLoan() {
        return loan;
    }

    public void setLoan(Loan loan) {
        this.loan = loan;
    }

    public Book getB() {
        return b;
    }

    public void setB(Book b) {
        this.b = b;
    }
    
    public Customer getCus() {
        
        return cus;
    }
    
    public void setCus(Customer cus) {
        this.cus = cus;
    }

    public Boolean getLoanButton(Book b) {
        if(b.getAvailability()){
            loanButton = false;
        }
        else{
            loanButton = true;
        }
        return loanButton;
    }

    public void setLoanButton(Boolean loanButton) {
        this.loanButton = loanButton;
    }
    
    public List<Loan> getUserLoan() {
        List<Loan> loans = new ArrayList<Loan>();
        for (Loan l : bookService.getAllLoans()){
            if (l.getUser().getName().equals(getCurrentUserName())) {
                loans.add(l);
            }
        }
        return loans;
            
    }
    
}

Ass2-war/web/customer/bookDetail.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition template="../masterpage.xhtml">
            <ui:define name="header">
                <ui:include src="customerHeader.xhtml" />
            </ui:define>
            <ui:define name="content">
                <div id="content">
                    <div class="titleBox">
                        <div class="clear"></div>
                        <h1>Book Detail</h1>
                        <div class="clear"></div>
                    </div>
                    <h:form>
                        <h:graphicImage name="#{commentController.bc.imgSource}" style="width: 400px; height: 500px; padding-right: 15px; float: left"/>
                        <h2><br/>Title: #{commentController.bc.title}</h2>
                        <p align="justify">
                            <br/>   
                            Year: #{commentController.bc.author}
                            <br/>
                            <br/>
                            Publisher: #{commentController.bc.publisher}
                            <br/>
                            <br/>
                            Publish Date: #{commentController.bc.publishDate}
                            <br/>
                            <br/>
                            Description: #{commentController.bc.description}
                        </p>
                        <br/>
                        <h:outputLabel value="Comment:" for="comment" style="float: left" />
                        <br/>
                        <h:inputTextarea id="comment" value="#{commentController.commentMsg}" style="float: left; width: 400px; height: 80px"/>
                        <br/>
                        <h:commandButton id="create" value="Comment" action="#{commentController.createComment()}" style="float: left"/>
                        <br/>
                        <div style="float: left">
                        <h3>Comments</h3>
                        <ui:repeat value="#{commentController.userComment}" var="item">
                            <div style="width: 400px; background: antiquewhite; margin: 5px">
                                <h3 align="left">Name: #{item.cus.name}</h3>
                                <h3 align="left"><h:outputText value="#{item.commentTime}">
                                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                                    </h:outputText></h3>
                                <p align="left">#{item.comment}</p>
                                
                            </div>
                        </ui:repeat>
                        </div>
                    </h:form>              
                </div>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

Ass2-war/web/customer/customerHeader.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition>
            <header>
                
                    <div class="logo">
                        <h1>Monash Books</h1>
                        <h3>Your choice</h3>
                    </div>
               
                <ul id="navbar">
                    <li><h:link outcome="#{bookController.resetBookCategories()}">Home</h:link></li>
                    <li><h:link outcome="manageLoan">Manage Loan</h:link></li>              
                    <li>
                        <h:form>
                            <h:inputText id="searchBoxInput" value="#{bookController.search}"/>

                            <h:commandButton id="submit" value="Search" actionListener="#{bookController.searchBook()}" 
                                             action="index">

                            </h:commandButton>
                        </h:form>
                    </li>
                    <li><b>Current user : </b>#{indexController.currentUsername}</li>
                    <li><h:form>
                            <h:commandButton action="#{indexController.logout()}" value="Logout"/>

                        </h:form></li>            
                </ul>
            </header>
        </ui:composition>
    </h:body>
</html>

Ass2-war/web/customer/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Customer Page</title>
        <link href="/faces/style.css" rel="stylesheet" type="text/css"/>
    </h:head>
    <h:body>
         <ui:composition template="../masterpage.xhtml">
            <ui:define name="header">
                 <ui:include src="customerHeader.xhtml" />
             </ui:define>
             <ui:define name="content">
                <div id="content">
                    <div class="titleBox">
                            <div class="clear"></div>
                            <h1>Book List</h1>
                            <div class="clear"></div>
                        </div>
                    <h:form>
                    <ui:repeat value="#{bookController.bookCategories}" var="item" varStatus="status">
                        <div class="row">
                            <h:link outcome="#{commentController.readBookCategory(item)}">
                                <h:graphicImage name="#{item.imgSource}" style="float: left"/>
                                <div class="info" style="float: left">
                                    Title: #{item.title}
                                    <br/>
                                    Author: #{item.author}
                                </div>
                            </h:link>
                            <h:commandButton action="#{bookController.markBook(item)}" value="#{bookController.markStatus(item)}" style="float: left; "/>
                                <div class="info" style="float: left">
                                <ui:repeat value="#{item.books}" var="book">
                                    <h:outputText value="Copy No: #{book.id}"/>
                                        <h:outputText value=" Availability: #{book.availability}"/>
                                        <h:commandButton id="loanButton" disabled="#{loanController.getLoanButton(book)}" action="#{loanController.createLoan(book)}" value="Loan" />
                                        <br/>
                                </ui:repeat>
                                </div>
                                
                        </div>
                    </ui:repeat> 
                    </h:form>
                    
                   

                </div>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

Ass2-war/web/customer/manageLoan.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition template="../masterpage.xhtml">
            <ui:define name="header">
                <ui:include src="customerHeader.xhtml" />
            </ui:define>
            <ui:define name="content">
                <div id="content">
                    <div class="titleBox">
                            <div class="clear"></div>
                            <h1>Loaned Book</h1>
                            <div class="clear"></div>
                    </div>
                    <f:view>
                        <h:form>
                            <h:dataTable value="#{loanController.userLoan}" var="item">
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="Id"/>
                                    </f:facet>
                                    <h:outputText value="#{item.id}"/>
                                </h:column>
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="User"/>
                                    </f:facet>
                                    <h:outputText value="#{item.user.name}"/>
                                </h:column>
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="Book"/>
                                    </f:facet>
                                    <h:outputText value="#{item.book.bookCategory.title}"/>
                                </h:column>
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="LoanDate"/>
                                    </f:facet>
                                    <h:outputText value="#{item.loanDate}">
                                        <f:convertDateTime pattern="MM/dd/yyyy" />
                                    </h:outputText>
                                </h:column>
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="Actions"/>
                                    </f:facet>
                                    <h:commandButton action="#{loanController.returnBook(item)}" value="Return" />
                                </h:column>
                            </h:dataTable>
                        </h:form>
                    </f:view>

                </div>
            </ui:define>
        </ui:composition>
    </h:body>
</html>