Ass2-war/src/java/controllers/ErrorController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package controllers;

import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;

/**
 *
 * @author Alex
 */
@Named(value = "errorController")
@SessionScoped
public class ErrorController implements Serializable {

    /**
     * Creates a new instance of ErrorController
     */
    private static String errorMessage;
    private String error;

    public String getError() {
        error = errorMessage;
        return error;
    }

    public void setError(String error) {
        this.error = error;
    }
    
    public static String getErrorMessage() {
        return errorMessage;
    }

    public static void setErrorMessage(String errorMessage) {
        ErrorController.errorMessage = errorMessage;
    }
    
}

Ass2-war/src/java/controllers/IndexController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package controllers;

import ejb.BookService;
import entities.*;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.ApplicationScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.servlet.http.HttpSession;

/**
 *
 * @author Alex
 */
@Named(value = "indexController")
@ApplicationScoped
public class IndexController {
    
    
    @EJB
    BookService bookService;
    private String currentUsername;

        
    
    public String getCurrentUsername() {
        FacesContext facesContext = FacesContext.getCurrentInstance();
        currentUsername = facesContext.getExternalContext().getRemoteUser();
        return currentUsername;
    }

    public void setCurrentUsername(String currentUsername) {
        this.currentUsername = currentUsername;
    }
    
    
    public List<Customer> getUsers() {
        return bookService.getAllUsers();
    }
    
    public List<BookCategory> getBookCategories() {
        return bookService.getAllBookCategorys();
    }
    public List<BookCategory> getMarkedBook() {
        List<BookCategory> bcs = new ArrayList<BookCategory>();
        for(BookCategory bc: getBookCategories()){
            if(bc.getCustomers().size()>0){
                bcs.add(bc);
            }
        }
        return bcs;
    }
    public List<Book> getBooks() {
        return bookService.getAllBooks();
    }
   
    public String logout() {
    FacesContext facesContext = FacesContext.getCurrentInstance();
    HttpSession httpSession = (HttpSession)facesContext.getExternalContext().getSession(false);
    httpSession.invalidate();
    
    return "/faces/index";
    }
}

Ass2-war/web/documentation.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition template="masterpage.xhtml">
            <ui:define name="content">
                <article style="width: 960px;text-align: left; padding-left: 20px">
                    <h1><br/>
                        Documentation</h1>
                    <p>
                        <br/>
                        Name: Guohua Li
                        <br/>
                        <br/>
                        Student Id: 23953721
                        <br/>
                        <br/>
                        Reference List:
                        <br/>
                        <br/>
                        [1]<b>Password Converter:</b>
                        http://stackoverflow.com/questions/5531455/how-to-encode-some-string-with-sha256-in-java
                        <br/>
                        <br/>
                        [2]<b>Authentication 403 Page redirect:</b>
                        http://blog.eisele.net/2013/01/jdbc-realm-glassfish312-primefaces342.html
                        <br/>
                        <br/>
                        [3]<b>Image source:</b>
                        http://www.softicons.com/free-icons/object-icons/somebooks-icons-by-c55inator/brown-book-icon
                        <br/>
                        <br/>
                        [4]<b>Css and image reference path:</b>
                        http://stackoverflow.com/questions/7376115/absolute-path-name-in-my-template-to-get-resources
                        <br/>
                        <br/>
                        [5]<b>jQuery datepicker in h:form:</b>
                        http://stackoverflow.com/questions/16565798/jquery-datepicker-doesnt-work-when-clicked-add-new-line-link
                    </p>
                </article>

            </ui:define>
        </ui:composition>
    </h:body>
</html>

Ass2-war/web/error.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Facelet Title</title>
        <link href="style.css" rel="stylesheet" type="text/css"/>
    </h:head>
    <h:body>
        <ui:composition template="masterpage.xhtml">
            <ui:define name="content">
                <div id="content">
                    <h1>Authentication Error</h1>
                    <p>The user credentials you have supplied are incorrect.</p>
                    <p>Please attempt to <h:link outcome="login" value="login" /> again.</p>
                </div>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

Ass2-war/web/footer.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition>
            <footer>
                <div class="clear"></div>
                <p>Copyright@ Guohua Li, all rights reserved</p>
            </footer>
        </ui:composition>
    </h:body>
</html>

Ass2-war/web/header.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
<h:body>
        <ui:composition>
            <header>
                <h:link outcome="/faces/index">
                    <div class="logo">
                        <h1>Monash Books</h1>
                        <h3>Your choice</h3>
                    </div>
                </h:link>
                <ul id="navbar">
                    <li><h:link outcome="/faces/index">Home</h:link></li>
                    <li><h:link outcome="/faces/customer/index">Customer Entry</h:link></li>
                    <li><h:link outcome="/faces/admin/index">Admin Entry</h:link></li>
                    <li><h:link outcome="/faces/documentation">Documentation</h:link></li>
                    <li><h:link outcome="/faces/registration">Registration</h:link></li>
                </ul>
            </header>
        </ui:composition>
    </h:body>
</html>

Ass2-war/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Home</title>     
    </h:head>
    <h:body>
        <ui:composition template="masterpage.xhtml">
            <ui:define name="content">
                <div id="content">
                        <div class="titleBox">
                            <div class="clear"></div>
                            <h1>Popular Books</h1>
                            <div class="clear"></div>
                        </div>
                        <div class="clear"></div>
                        <ui:repeat value="#{indexController.markedBook}" var="item" varStatus="status">
                            <div class="row">
                                <h:graphicImage name="#{item.imgSource}" style="float: left"/>
                                <h3 align="left">Title: #{item.title}</h3>
                                <p align="justify">Description: #{item.description}</p>
                            </div>
                            <div class="clear"></div>
                        </ui:repeat>
                </div>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

Ass2-war/web/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Login</title>
        <link href="/faces/style.css" rel="stylesheet" type="text/css"/>
    </h:head>
    <h:body>
        <ui:composition template="masterpage.xhtml">
            <ui:define name="content">
                <div id="content">
                    <h1>Login</h1>
                    <div class="clear"></div>
                    <form method="POST" action="j_security_check">
                        <label for="j_username">Username:</label>
                        <input type="text" name="j_username" />
                        <label for="j_password">Password:</label>
                        <input type="password" name="j_password" />
                        <input type="submit" value="Submit"/>
                    </form>
                </div>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

Ass2-war/web/masterpage.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Movies</title>

        <h:outputStylesheet name="style.css"/>
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
        <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
        <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
        <script>
            $(function() {
                $("#myForm .datepicker").datepicker();
            });
        </script>
    </h:head>
    <h:body>
        <div class ="container">
            <ui:insert name="header">
                <ui:include src="header.xhtml" />
            </ui:insert>
            <div class="clear"></div>         
            <ui:insert name="content">
            </ui:insert>
            <div class="clear"></div>
            <ui:insert name="footer">
                <ui:include src="footer.xhtml" />
            </ui:insert>
        </div>
    </h:body>
</html>

Ass2-war/web/registration.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition template="masterpage.xhtml">
            <ui:define name="content">
                <div id="content">
                       <div class="titleBox">
                            <div class="clear"></div>
                            <h1>Registration</h1>
                            <div class="clear"></div>
                        </div>
                    <div class="clear"></div>
                    <div class="container">
                    <f:view>                       
                        <h:form>                            
                            <h:panelGrid columns="2" style=" margin-left: 350px">
                                <h:outputLabel value="Name:" for="name" />
                                <h:inputText id="name" value="#{customerController.customer.name}"
                                             title="name" />
                                <h:outputLabel value="Password:" for="password" />
                                <h:inputText id="password" value="#{customerController.password}"
                                             title="password" />
                                <h:outputLabel value="Group:" for="group" />
                                <h:selectOneMenu id="group" value="#{customerController.groupName}">
                                    <f:selectItems value="#{customerController.group}"/> </h:selectOneMenu>

                            </h:panelGrid>
                            <div class="clear"></div>
                            <h:commandButton id="create" 
                                             value="Create" rendered="#{empty customerController.customer.id}" action="#{customerController.create()}"/>
                            <h:commandButton id="update" 
                                             value="Update" rendered="#{not empty customerController.customer.id}" action="#{customerController.update()}"/>
                            <h:commandButton id="back" value="Back" action="index"/>
                        </h:form>
                    </f:view>
                    </div>
                </div>
            </ui:define>
        </ui:composition>
    </h:body>
</html>